---
- name: running system_filesystem tasks
  include_tasks: system_filesystem.yml
  loop: "{{ system_filesystem | dict2items }}"
  loop_control:
    label: "{{ system_filesystem_item['key'] }}"
    loop_var: system_filesystem_item
  when:
    system_filesystem is defined
